using CommunityBankTellerAPI.Data;
using Microsoft.EntityFrameworkCore;
using CommunityBankTellerAPI.Services;
using CommunityBankTellerAPI.Services.Interfaces;
using System.Reflection;
using CommunityBankTellerAPI.Repositories.Interfaces;
using CommunityBankTellerAPI.Repositories;
using CommunityBankTellerAPI.Middleware;

namespace CommunityBankTellerAPI
{
    public partial class Program
    {
        public static void Main(string[] args)
        {
            var builder = WebApplication.CreateBuilder(args);

            // Only configure the real database if we're not in the "Testing" environment.
            if (!builder.Environment.IsEnvironment("Testing"))
            {
                builder.Services.AddDbContext<AppDbContext>(options =>
                    options.UseNpgsql(builder.Configuration.GetConnectionString("DefaultConnection")));
            }

            // Add services to the container.
            builder.Services.AddControllers()
                .AddJsonOptions(options =>
                {
                    options.JsonSerializerOptions.Converters.Add(new System.Text.Json.Serialization.JsonStringEnumConverter());
                });

            // Register repositories and services for dependency injection
            builder.Services.AddScoped<IUnitOfWork, UnitOfWork>();

            builder.Services.AddScoped<ICustomerRepository, CustomerRepository>();
            builder.Services.AddScoped<IAccountRepository, AccountRepository>();
            builder.Services.AddScoped<ITransactionRepository, TransactionRepository>();
            builder.Services.AddScoped<ILedgerRepository, LedgerRepository>();

            builder.Services.AddScoped<ICustomerService, CustomerService>();
            builder.Services.AddScoped<IAccountService, AccountService>();
            builder.Services.AddScoped<ITransactionService, TransactionService>();
            builder.Services.AddScoped<ILedgerService, LedgerService>();

            // Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
            builder.Services.AddEndpointsApiExplorer();
            // Configure Swagger to include XML comments for better documentation
            builder.Services.AddSwaggerGen(options =>
            {
                // Set the path to the XML documentation file generated by the compiler
                var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
                // Combine the base directory with the XML file name to get the full path
                var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
                // Instruct Swagger to include the XML comments in the generated API documentation
                options.IncludeXmlComments(xmlPath);
            });

            // Build the app and configure the middleware pipeline
            var app = builder.Build();

            // middleware must be first to catch all unhandled exceptions
            app.UseMiddleware<ExceptionHandlingMiddleware>();

            // Enable Swagger in development environments for API documentation and testing
            if (app.Environment.IsDevelopment())
            {
                app.UseSwagger();
                app.UseSwaggerUI();
            }

            // Enforce HTTPS in production environments
            app.UseHttpsRedirection();

            // Authorization middleware should be placed after authentication and before endpoint mapping
            app.UseAuthorization();
            // Map controller endpoints
            app.MapControllers();
            // Run the application
            app.Run();
        }
    }
}
